# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-ZTXFW04G7P"

# UI configs
title: "Photography by Shioji Ryosuke"
subtitle: "See the world through my eyes!"
author: "Shioji Ryosuke"
header:
 title: "Photography"
 subtitle: "by Shioji Ryosuke"
footer:
 name: "ご来訪いただきありがとうございます。Shioji Ryosukeと申します。"
 bio: "写真撮影が好きな関西の大学生です。WEBアプリ開発にも取り組んでいます。"
 github: ""
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://x.com/Alshiel_1280"
  instagram: "https://www.instagram.com/r.s0g_/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/Alshiel-1280"
