# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-ZTXFW04G7P"

# UI configs
title: "Photography by Shioji Ryosuke"
subtitle: "See the world through my eyes!"
author: "Shioji Ryosuke"
header:
 title: "Photography"
 subtitle: "by Shioji Ryosuke"
footer:
 name: "ご来訪いただきありがとうございます。<br>Shioji Ryosukeと申します。"
 bio: "<h2>経歴</h2>2023年3月　宮城県仙台第二高等学校卒業<br>2023年4月　関西大学経済学部経済学科入学<br><br><h2>カテゴリ</h2>風景・ポートレート・コスプレ・馬<br><br><h2>所持機材</h2>ボディ：Z6Ⅱ<br>レンズ：TAMRON 28-75mm F2.8, Nikkor AF-S 105mm F1.4E, Nikkor AF-P 70-300mm F4.5-5.6E<br>周辺機器：Godox AD200pro, Godox TT600, Godox XproⅡ-N, 他三脚・ソフトボックス等"
 github: ""
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://x.com/Alshiel_1280"
  instagram: "https://www.instagram.com/r.s0g_/"
  dribbble: ""
  linkedin: "https://www.linkedin.com/in/shioji-ryosuke"
  github: "https://www.github.com/Alshiel-1280"
